spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: create


  flyway:
    enabled: false
    baseline-on-migrate: false

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
