spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    show_sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        highlight_sql: false
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: none

server:
  port: 5000

gpt:
  key: ${GPT_API_KEY}
