SET
FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE member;
TRUNCATE TABLE chat;
TRUNCATE TABLE question_and_answer;
TRUNCATE TABLE comment;
TRUNCATE TABLE chat_like;
TRUNCATE TABLE keyword;
TRUNCATE TABLE event_history;
SET
FOREIGN_KEY_CHECKS = 1;
